---
title: "PSTAT122_HW2"
output: html_document
date: "2025-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
pan <- c(12.70, 12.30, 12.40, 12.80, 12.60,
12.50, 12.20, 12.70, 12.40, 12.60)
grilled <- c(11.80, 11.55, 11.75, 11.65, 11.50,
11.75, 11.30, 12.10, 11.50, 11.45)

burgers_df <- data.frame(
sat_fat = c(pan, grilled),
method = c(rep("pan", length(pan)),
            rep("grilled", length(grilled)))
)

sample(burgers_df$sat_fat)
```

```{r}
burgers_perm <- burgers_df # temporarily copy the whole df
burgers_perm$sat_fat <- sample(burgers_perm$sat_fat)

t.test(sat_fat ~ method, data = burgers_perm)$statistic
```
```{r}
perm_t <- NA

reps <- 10000

for(i in 1:reps){
burgers_perm <- burgers_df
burgers_perm$sat_fat <- sample(burgers_perm$sat_fat)
perm_t[i] <- t.test(sat_fat ~ method,
data=burgers_perm)$statistic
}
t0 <- t.test(sat_fat ~ method, data=burgers_df)$statistic

sum(abs(perm_t) >= abs(t0))/reps
sum(abs(perm_t) >= abs(t0))/reps
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
